### ISSUE TITLE
Problems getting ND4J working in Windows with GPU backend

### ISSUE THREAD

**Issue by globalcaos** [SkymindIO/nd4j#12]
Hi there. I am trying to use ND4J in Windows 7 64 with the JCublas backend, and when I run the ElementWiseOperationExample.java it dumps this:

     SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
     SLF4J: Defaulting to no-operation (NOP) logger implementation
     SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
     Exception in thread "main" java.lang.UnsatisfiedLinkError: Could not load the native library.
     Error while loading native library "JCublas-windows-x86_64" with base name "JCublas"
     Operating system name: Windows 7
     Architecture         : amd64
     Architecture bit size: 64
     Stack trace from the attempt to load the library as a resource:
     java.lang.NullPointerException: No resource found with name '/lib/JCublas-windows-x86_64dll'
	     at jcuda.LibUtils.loadLibraryResource(LibUtils.java:149)
	     at jcuda.LibUtils.loadLibrary(LibUtils.java:83)
	     at jcuda.jcublas.JCublas.initialize(JCublas.java:82)
	     at jcuda.jcublas.JCublas.<clinit>(JCublas.java:70)
	     at org.nd4j.linalg.jcublas.SimpleJCublas.<clinit>(SimpleJCublas.java:90)
	     at org.nd4j.linalg.jcublas.JCublasWrapper.axpy(JCublasWrapper.java:69)
	     at org.nd4j.linalg.api.ndarray.BaseNDArray.addi(BaseNDArray.java:2703)
	     at org.nd4j.linalg.api.ndarray.BaseNDArray.addi(BaseNDArray.java:2677)
	     at org.nd4j.linalg.api.ndarray.BaseNDArray.doColumnWise(BaseNDArray.java:2012)
	     at org.nd4j.linalg.api.ndarray.BaseNDArray.addiColumnVector(BaseNDArray.java:2276)
	     at org.nd4j.linalg.api.ndarray.BaseNDArray.addColumnVector(BaseNDArray.java:2287)
	     at org.nd4j.examples.ElementWiseOperationExample.main(ElementWiseOperationExample.java:43)
	     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	     at java.lang.reflect.Method.invoke(Method.java:606)
	     at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
     Stack trace from the attempt to load the library as a file:
     java.lang.UnsatisfiedLinkError: no JCublas-windows-x86_64 in java.library.path
	     at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1886)
	     at java.lang.Runtime.loadLibrary0(Runtime.java:849)
	     at java.lang.System.loadLibrary(System.java:1088)
	     at jcuda.LibUtils.loadLibrary(LibUtils.java:94)
	     at jcuda.jcublas.JCublas.initialize(JCublas.java:82)
	     at jcuda.jcublas.JCublas.<clinit>(JCublas.java:70)
	     at org.nd4j.linalg.jcublas.SimpleJCublas.<clinit>(SimpleJCublas.java:90)
	     at org.nd4j.linalg.jcublas.JCublasWrapper.axpy(JCublasWrapper.java:69)
	     at org.nd4j.linalg.api.ndarray.BaseNDArray.addi(BaseNDArray.java:2703)
	     at org.nd4j.linalg.api.ndarray.BaseNDArray.addi(BaseNDArray.java:2677)
	     at org.nd4j.linalg.api.ndarray.BaseNDArray.doColumnWise(BaseNDArray.java:2012)
	     at org.nd4j.linalg.api.ndarray.BaseNDArray.addiColumnVector(BaseNDArray.java:2276)
	     at org.nd4j.linalg.api.ndarray.BaseNDArray.addColumnVector(BaseNDArray.java:2287)
	     at org.nd4j.examples.ElementWiseOperationExample.main(ElementWiseOperationExample.java:43)
	     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	     at java.lang.reflect.Method.invoke(Method.java:606)
	     at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)

	     at jcuda.LibUtils.loadLibrary(LibUtils.java:126)
	     at jcuda.jcublas.JCublas.initialize(JCublas.java:82)
	     at jcuda.jcublas.JCublas.<clinit>(JCublas.java:70)
	     at org.nd4j.linalg.jcublas.SimpleJCublas.<clinit>(SimpleJCublas.java:90)
	     at org.nd4j.linalg.jcublas.JCublasWrapper.axpy(JCublasWrapper.java:69)
	     at org.nd4j.linalg.api.ndarray.BaseNDArray.addi(BaseNDArray.java:2703)
	     at org.nd4j.linalg.api.ndarray.BaseNDArray.addi(BaseNDArray.java:2677)
	     at org.nd4j.linalg.api.ndarray.BaseNDArray.doColumnWise(BaseNDArray.java:2012)
	     at org.nd4j.linalg.api.ndarray.BaseNDArray.addiColumnVector(BaseNDArray.java:2276)
	     at org.nd4j.linalg.api.ndarray.BaseNDArray.addColumnVector(BaseNDArray.java:2287)
	     at org.nd4j.examples.ElementWiseOperationExample.main(ElementWiseOperationExample.java:43)
	     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	     at java.lang.reflect.Method.invoke(Method.java:606)
	     at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)

Process finished with exit code 1

While debugging I realized in [SimpleJCublas.java line #75](https://github.com/SkymindIO/nd4j/blob/master/nd4j-jcublas-parent/nd4j-jcublas-common/src/main/java/org/nd4j/linalg/jcublas/SimpleJCublas.java#L75), it fails to find the CUDA libraries because it is looking in

     C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v6.5\Lib

and the libraries in Windows are inside 

     C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v6.5\lib\x64

instead.

When I fix this (by copying the libraries where you expect them to be) and debug I now see it finds the libraries, but still dumps the exact same error when running. Was anyone able to make it run in Windows? Can you guys fix this bug??

**Comment by agibsonccc** [comment]
Done.
